name: Build Firmware and Apps

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v6.0.1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build firmware
        run: |
          . /opt/esp/idf/export.sh
          idf.py build

      - name: Install app dependencies
        run: |
          apt-get update
          apt-get install -y vim-common

      - name: Build all apps
        run: |
          set -e
          . /opt/esp/idf/export.sh

          mkdir -p build/apps

          # Generate OS symbol table
          scripts/gen_symtab.sh build/esposito.elf build/os_symbols.ld

          # Build each app
          for app_dir in apps/*/; do
              if [ -f "${app_dir}app.c" ]; then
                  scripts/build_app.sh "${app_dir}app.c" build/apps
              fi
          done

      - name: Package for artifact
        run: |
          set -e

          mkdir -p system
          cp build/esposito.bin system/firmware.bin

          mkdir -p build/package/apps

          for app_elf in build/apps/*.elf; do
              app_name=$(basename "$app_elf" .elf)
              mkdir -p "build/package/apps/${app_name}"
              cp "$app_elf" "build/package/apps/${app_name}/program.elf"

              manifest="apps/${app_name}/manifest.cfg"
              if [ -f "$manifest" ]; then
                  cp "$manifest" "build/package/apps/${app_name}/manifest.cfg"
              fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: firmware-and-apps
          path: |
            system/firmware.bin
            build/package/apps/**
            fonts/*.fpack
            build/bootloader/bootloader.bin
		        build/partition_table/partition-table.bin
		        build/esposito.bin
		        build/ota_data_initial.bin

